### ISSUE TITLE
There is an inconsistency between the template and altas?

### ISSUE THREAD

**Issue by doulemint** [grandjeanlab/MultiRat#1]
When I ran preprocessing [ script](https://github.com/grandjeanlab/MultiRat/blob/9f565afbbe51dee4dba174a7230d3112fee5a70e/scripts/proj_submitjobs.ipynb), I ran into this error from rabies images:

> The file /template/SIGMA_Wistar_Rat_Brain_TemplatesAndAtlases_Version1.1/SIGMA_Rat_Brain_Atlases/SIGMA_Anatomical_Atlas/SIGMA_Anatomical_Brain_Atlas.nii does not appear to overlap with provided template /template/SIGMA_Wistar_Rat_Brain_TemplatesAndAtlases_Version1.1/SIGMA_Rat_Anatomical_Imaging/SIGMA_Rat_Anatomical_InVivo_Template/SIGMA_InVivo_Brain_Template.nii 

they seemly have different size and aligned to different spaces?

```
3dinfo /template/SIGMA_Wistar_Rat_Brain_TemplatesAndAtlases_Version1.1/SIGMA_Rat_Anatomical_Imaging/SIGMA_Rat_Anatomical_InVivo_Template/SIGMA_InVivo_Brain_Template.nii
++ 3dinfo: AFNI version=AFNI_20.3.03 (Dec  7 2020) [64-bit]

Dataset File:    /template/SIGMA_Wistar_Rat_Brain_TemplatesAndAtlases_Version1.1/SIGMA_Rat_Anatomical_Imaging/SIGMA_Rat_Anatomical_InVivo_Template/SIGMA_InVivo_Brain_Template.nii
Identifier Code: NII_n31pxrqN0SUbpM1S9tWqDg  Creation Date: Sat May 21 21:55:35 2022
Template Space:  TLRC
Dataset Type:    Anat Bucket (-abuc)
Byte Order:      LSB_FIRST {assumed} [this CPU native = LSB_FIRST]
Storage Mode:    NIFTI
Storage Space:   7,143,424 (7.1 million) bytes
Geometry String: "MATRIX(-0.15,0,0,9.44,0,-0.15,0,17.81,0,0,0.15,-6.765):128,218,128"
Data Axes Tilt:  Plumb
Data Axes Orientation:
  first  (x) = Left-to-Right
  second (y) = Posterior-to-Anterior
  third  (z) = Inferior-to-Superior   [-orient LPI]
R-to-L extent:    -9.610 [R] -to-     9.440 [L] -step-     0.150 mm [128 voxels]
A-to-P extent:   -14.740 [A] -to-    17.810 [P] -step-     0.150 mm [218 voxels]
I-to-S extent:    -6.765 [I] -to-    12.285 [S] -step-     0.150 mm [128 voxels]
Number of values stored at each pixel = 1
  -- At sub-brick #0 '?' datum type is short
```

```
3dinfo /template/SIGMA_Wistar_Rat_Brain_TemplatesAndAtlases_Version1.1/SIGMA_Rat_Brain_Atlases/SIGMA_Anatomical_Atlas/SIGMA_Anatomical_Brain_Atlas.nii.gz
++ 3dinfo: AFNI version=AFNI_20.3.03 (Dec  7 2020) [64-bit]

Dataset File:    /template/SIGMA_Wistar_Rat_Brain_TemplatesAndAtlases_Version1.1/SIGMA_Rat_Brain_Atlases/SIGMA_Anatomical_Atlas/SIGMA_Anatomical_Brain_Atlas.nii.gz
Identifier Code: NII_DeJGSOJNSF-zX8FkVqSwyg  Creation Date: Sat May 21 21:55:18 2022
Template Space:  TLRC
Dataset Type:    Anat Bucket (-abuc)
Byte Order:      LSB_FIRST {assumed} [this CPU native = LSB_FIRST]
Storage Mode:    NIFTI
Storage Space:   65,445,120 (65 million) bytes
Geometry String: "MATRIX(-0.09,0,0,11.61,0,-0.09,0,17.6175,0,0,0.09,-6.96597):260,342,184"
Data Axes Tilt:  Plumb
Data Axes Orientation:
  first  (x) = Left-to-Right
  second (y) = Posterior-to-Anterior
  third  (z) = Inferior-to-Superior   [-orient LPI]
R-to-L extent:   -11.700 [R] -to-    11.610 [L] -step-     0.090 mm [260 voxels]
A-to-P extent:   -13.073 [A] -to-    17.618 [P] -step-     0.090 mm [342 voxels]
I-to-S extent:    -6.966 [I] -to-     9.504 [S] -step-     0.090 mm [184 voxels]
Number of values stored at each pixel = 1
  -- At sub-brick #0 '?' datum type is float
```

I hope I make my problem clear. I might missed out some steps. Could anyone helps me?

**Comment by grandjeanlab** [comment]
Hi,
this is correct. I have informed the author of the template, but I don't kbow if it got updated. 

Send me an email (joanes.grandjean@radboudumc.nl) and I will send you a copy of the atlas resampled into the template

**Comment by DavidBarriere** [comment]
Hi,
I am fixing it for the next version of the SIGMA.
A corrected version is coming.

David

**Comment by grandjeanlab** [comment]
I head from @DavidBarriere that the atlas was corrected and a new version is uploaded. @doulemint could you check if it works now?

**Comment by Hierakonpolis** [comment]
I am experiencing the same issue, I tried using the following files from all dowloadable versions of the atlas (1.1, 1.11, 1.2)

Atlas:
`SIGMA_Rat_Brain_Atlases/SIGMA_Anatomical_Atlas/SIGMA_Anatomical_Brain_Atlas.nii
`
Template:
`SIGMA_Rat_Anatomical_Imaging/SIGMA_Rat_Anatomical_InVivo_Template/SIGMA_InVivo_Brain_Template.nii`

The affine matrices also seem to indicate that these volumes would reside in different spaces.

**Comment by gdevenyi** [comment]
@DavidBarriere?

**Comment by DavidBarriere** [comment]
Hi guys,
Header checking and fixing in progress.

**Comment by DavidBarriere** [comment]
Could you please download and try the **Sigma Wistar Rat Brain Templates and Atlases Version1.2.1** on NITRC platform  ?
https://www.nitrc.org/projects/sigma_template

You will find little changes in **SIGMA_Rat_Brain_Atlases/SIGMA_Anatomical_Atlas** folder with two additional folders :
- **ExVivo_Atlas** with the _ex vivo_ SIGMA atlas (0.09µm isotropic)
- **InVivo_Atlas** with the _in vivo_ SIGMA atlas (0.150µm isotropic) 

I also add _in vivo_ GM, WM and CSF masks within the **SIGMA_Rat_Anatomical_Imaging/SIGMA_Rat_Anatomical_InVivo_Template** folder
- SIGMA_InVivo_CSF_mask.nii
- SIGMA_InVivo_GM_mask.nii
- SIGMA_InVivo_WM_mask.nii

Please send here your feedback.

D
